version: '3.8'

services:
  db:
    image: timescale/timescaledb:2.5.0-pg14
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db_data:
